#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# Ensure composer directory exists and has correct permissions
if [ ! -d /.composer ]; then
    mkdir /.composer
    chmod -R ugo+rw /.composer
    chown -R sail:sail /.composer
fi

# Set permissions for Laravel storage and bootstrap cache
chown -R sail:sail /var/www/html/logs
chown -R sail:sail /var/www/html/storage
chown -R sail:sail /var/www/html/bootstrap/cache

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
